export const permissions = {
  dashboardRead: 'dashboard.read',
  employeeRead: 'employee.read',
  employeeCreate: 'employee.write',
  employeeUpdate: 'employee.write',
  employeeDelete: 'employee.delete',
  employeeWrite: 'employee.write',
  attendanceReadSelf: 'attendance.read.self',
  attendanceReadTeam: 'attendance.read.team',
  attendanceReadDepartment: 'attendance.read.department',
  attendanceReadAll: 'attendance.read.all',
  attendanceWriteSelf: 'attendance.write.self',
  attendanceRegularizeSelf: 'attendance.regularize.self',
  attendanceApproveTeam: 'attendance.approve.team',
  attendanceRead: 'attendance.read',
  attendanceWrite: 'attendance.write',
  leaveRead: 'leave.read',
  leaveWrite: 'leave.write',
  leaveApprove: 'leave.approve',
  jobRead: 'job.read',
  jobWrite: 'job.write',
  applicationRead: 'application.read',
  applicationWrite: 'application.write',
  interviewManage: 'interview.manage',
  rbacManage: 'rbac.manage',
  employeeDirectoryRead: 'employee.directory.read',
  employeeUserManage: 'employee.user.manage'
} as const;
