export const endpoints = {
  auth: {
    login: "/auth/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    changePassword: "/auth/change-password",
    me: "/auth/me",
  },
  dashboard: {
    stats: "/dashboard/stats",
    activity: "/dashboard/activity",
  },
  notifications: "/notifications",
  departments: {
    list: '/departments',
    detail: (id: string) => `/departments/${id}`,
    teams: (id: string) => `/departments/${id}/teams`,
    assignEmployee: (id: string) => `/departments/${id}/employees`
  },
  employees: "/employees",
  employeeReportingManagerOptions: '/employees/reporting-manager-options',
  employeeReportingManager: (id: string) => `/employees/${id}/reporting-manager`,
  employeeProfile: (id: string) => `/employees/${id}/profile`,
  employeeProfilePersonal: (id: string) => `/employees/${id}/profile/personal`,
  employeeProfileContact: (id: string) => `/employees/${id}/profile/contact`,
  employeeProfileEmployment: (id: string) => `/employees/${id}/profile/employment`,
  employeeProfileEmergency: (id: string) => `/employees/${id}/profile/emergency`,
  employeeRevealSensitive: (id: string) => `/employees/${id}/profile/reveal-sensitive`,
  employeeDocuments: (id: string) => `/employees/${id}/documents`,
  employeeDocument: (id: string, documentId: string) => `/employees/${id}/documents/${documentId}`,
  employeeBankChangeRequest: (id: string) => `/employees/${id}/bank-change-request`,
  employeeBankChangeApprove: (id: string, reqId: string) => `/employees/${id}/bank-change-request/${reqId}/approve`,
  employeeBankChangeReject: (id: string, reqId: string) => `/employees/${id}/bank-change-request/${reqId}/reject`,
  employeeImportTemplate: '/employees/import/template',
  employeeBulkImport: '/employees/bulk-import',
  employeeBulkImportConfirm: '/employees/bulk-import/confirm',
  employeeExport: '/employees/export',
  employeeBulkUpdate: '/employees/bulk-update',
  attendance: "/attendance",
  attendanceToday: "/attendance/today",
  attendanceAnalytics: "/attendance/analytics",
  attendanceRegularizations: "/attendance/regularizations",
  attendanceRegularize: "/attendance/regularize",
  leaveRequests: "/leave/requests",
  leaveApply: "/leave/apply",
  leaveCancel: (id: string) => `/leave/requests/${id}/cancel`,
  leaveBalance: "/leave/balances",
  leaveCalendarView: "/leave/calendar",
  leaveHolidays: "/calendar/holidays",
  leaveBalances: "/leaves/balances",
  leaveCalendar: "/leaves/calendar",
  leaveTypes: "/leave-types",
  leavePendingApprovals: "/leaves/pending-approvals",
  leaves: "/leaves",
  recruitment: {
    jobs: "/jobs",
    publishedJobs: "/jobs/published",
    candidates: "/candidates",
    candidateDetail: (id: string) => `/candidates/${id}/detail`,
    candidateActivity: (id: string) => `/candidates/${id}/activity`,
    candidateStage: (id: string) => `/candidates/${id}/stage`,
    candidateNotes: (id: string) => `/candidates/${id}/notes`,
    applications: "/applications",
    interviews: "/interviews",
    quickCreate: "/recruitment/quick-create",
  },
  preOnboarding: {
    list: "/pre-onboarding",
    detail: (id: string) => `/pre-onboarding/${id}`,
    fromOffer: (offerId: string) => `/pre-onboarding/from-offer/${offerId}`,
    regenerateToken: (id: string) => `/pre-onboarding/${id}/regenerate-token`,
    verify: (id: string) => `/pre-onboarding/${id}/verify`,
    verifyDocument: (id: string) => `/pre-onboarding/${id}/verify-document`,
    bulkApprove: (id: string) => `/pre-onboarding/${id}/bulk-approve`,
    sendBack: (id: string) => `/pre-onboarding/${id}/send-back`,
    approve: (id: string) => `/pre-onboarding/${id}/approve`,
    convert: (id: string) => `/pre-onboarding/${id}/convert`,
    portal: (token: string) => `/onboarding-portal/${token}`,
    portalPersonal: (token: string) => `/onboarding-portal/${token}/personal`,
    portalContact: (token: string) => `/onboarding-portal/${token}/contact`,
    portalIdentity: (token: string) => `/onboarding-portal/${token}/identity`,
    portalBank: (token: string) => `/onboarding-portal/${token}/bank`,
    portalEmergency: (token: string) => `/onboarding-portal/${token}/emergency`,
    portalDocuments: (token: string) => `/onboarding-portal/${token}/documents`,
    portalSubmit: (token: string) => `/onboarding-portal/${token}/submit`,
  },
  onboarding: {
    config: "/onboarding/config",
    myProgress: "/onboarding/my-progress",
    submit: "/onboarding/submit",
    review: (employeeId: string) => `/onboarding/${employeeId}/review`,
    activate: (employeeId: string) => `/onboarding/${employeeId}/activate`,
    upload: "/onboarding/documents/upload",
  },
  offerLetters: "/offer-letters",
  offerLetterDetail: (id: string) => `/offer-letters/${id}`,
  offerLetterPreview: (id: string) => `/offer-letters/${id}/preview`,
  offerLetterDownload: (id: string) => `/offer-letters/${id}/download`,
  offerLetterPdfPreview: "/offer-letters/pdf/preview",
  offerLetterStatus: (id: string) => `/offer-letters/${id}/status`,
  offerLetterRestore: (id: string) => `/offer-letters/${id}/restore`,
  offerLetterGenerate: "/offer-letters/generate",
  templates: "/templates",
  templateValidate: "/templates/validate",
  templatePreview: "/templates/preview",
  templateVersions: (id: string) => `/templates/${id}/versions`,
  templateUploadImage: "/templates/upload-image",
  templateSetDefault: (id: string) => `/templates/${id}/set-default`,
  roles: "/rbac/roles",
  permissions: "/rbac/permissions",
  permissionMatrix: "/rbac/permission-matrix",
  settings: "/settings",
  settingsHolidays: "/settings/holidays",
  activityLogs: "/activity-logs",
  auditLogs: "/audit-logs",
  profile: "/profile",
  tasks: "/tasks",
  tasksAssigneeOptions: "/tasks/assignee-options",
  tasksAnalyticsSelf: "/tasks/analytics/self",
  tasksAnalyticsTeam: "/tasks/analytics/team",
  taskDetail: (id: string) => `/tasks/${id}`,
  taskComments: (id: string) => `/tasks/${id}/comments`,
  taskComment: (id: string) => `/tasks/comments/${id}`,
  taskStatus: (id: string) => `/tasks/${id}/status`,
  config: {
    list: "/config",
    byKey: (key: string) => `/config/${key}`,
  },
} as const;
